### ISSUE TITLE
Some other omissions: handshake, auth

### ISSUE THREAD

**Issue by Thulinma** [zenomt/rtmp-errata-addenda#1]
Hey there! Thanks for taking the time to actually write these errata - finally having an official reference for these is great. 👍

## Handshake

An omission from the RTMP spec that I do not see addressed is the handshake: the original RTMP spec says to send random bytes and then return a copy of the received random bytes from the other side (I simplified a little for sake of brevity), while in reality the handshake hides an additional verification that you're connected to a "genuine" Adobe server/client. If this verification fails, H264 capabilities are disabled (at least by the official flash client versions I've personally tested - but this is all many years ago and testing it again today is... painfully complicated, to say the least).

Considering that...
- Flash player has effectively gone the way of the dodo, leaving only "non-official" player implementations in actual use (which **usually** ignore this verification - but not always).
- The verification process is now public knowledge (the algorithm is easily found with a little searching in unofficial places, and also part of many open source media server implementations)

... I think it would be worthwhile to actually note this algorithm and the effect it had/has on playback in Flash Player in these errata, or at the very least to include some wording that the returned handshake data should never be checked for integrity (being an actual echo of the sent data; since it may not be). And perhaps - if verification is implemented at all - discourage checking for success, since limiting the use of H264 in this day and age seems a little moot.

## Auth

Another omission is the username/password authentication mechanism. Specifically, the method when the server may return an error message with a description field containing `?authmod=adobe`, which seems to be the "official" way to handle username/password authentication and has de-facto become the standard in the industry as far as I'm aware (I _think_ there exists only one alternative, which is not in widespread use).
In particular, I'd like to see a note that the description field does _not_ make use of the usual query param encoding for regular URLs. The `+` symbol should not be decoded to space (common practice for URL params), but instead used as-is. Considering base64 encoding is used in these fields and the `+` symbol is part of the base64 character set, I'd say this is an important detail.

**Comment by zenomt** [comment]
re the handshake: i intentionally didn't say anything about the cryptographic handshake, and in fact that was what i was referring to in the Introduction section where i say

> It does not address private or undocumented extensions for which interoperation is not desired by the extending parties.

i helped create the cryptographic handshake, so i happen to know that interoperation was "not desired by the extending parties". it would not be appropriate for me to describe it in any way.

i'll try to think of the best way, using BCP 14 terms, to describe how endpoints that don't care about this should ignore it.

for interoperation with Flash Player or AIR, if you want to use H.264, you can just [use RTMFP](https://github.com/zenomt/rtmfp-cpp) instead, since H.264 is not restricted with that transport. :)

re auth: i'll check to see what Adobe Media Server does when it wants a username/password and you don't or give it the wrong one. as far as the protocol is concerned, it should be sufficient to describe that `connect` can take additional parameters of any types, that they **can** be strings, some servers **might** interpret them as usernames and passwords, and an auth failure should be like any other connect failure resulting in an `_error` and an appropriate `code`. anything in the `description` (from a protocol level) shouldn't be considered as anything other than informative and implementation-specific. i'll think about what's most appropriate to clarify here.

also see my companion [RTMP Family URI Schemes](https://zenomt.github.io/rtmp-errata-addenda/rtmp-uris#userinfo) doc section on _userinfo_.

**Comment by zenomt** [comment]
regarding auth: the `authmod=adobe` stuff is not part of RTMP nor even part of a stock Adobe Media Server installation; it is part of application-specific Adobe Primetime behavior and the "authentication module". see https://helpx.adobe.com/primetime/packagers/live_packager_getting_started.pdf and search for `authmod` for an explanation of this application-specific authentication protocol. note too that Flash Player and AIR won't deal with this protocol automatically; the connection rejections and further auth handshaking must all be done in ActionScript.

however, reading how this module works (and how it uses query parameters in the RTMP URI) is pushing me to update the description of the `app` property in the `connect` command's Command Object. Flash Player and AIR include any URI query parameters in the `app` property, but my description currently just says to include the URI's path minus any leading slash. the next rev (coming shortly) will bring the description in line with Flash Player/AIR behavior, since it's _probably_ required to implement Primetime auth.

**Comment by zenomt** [comment]
updated. please see
* [handshake](https://zenomt.github.io/rtmp-errata-addenda/rtmp-errata-addenda.html#name-chunk-stream-handshake-2)
* [app](https://zenomt.github.io/rtmp-errata-addenda/rtmp-errata-addenda.html#name-app-2)
* [optional user arguments](https://zenomt.github.io/rtmp-errata-addenda/rtmp-errata-addenda.html#name-optional-user-arguments-2)

(though the Primetime auth method you referred to appears to use URI query parameters and not optional user arguments to the `connect` command; however, that needed to be addressed anyway)

**Comment by zenomt** [comment]
i also added a [section on Authentication](https://zenomt.github.io/rtmp-errata-addenda/rtmp-errata-addenda.html#name-authentication-2) that links to the Primetime Live Packager document, and gives examples of other ways of doing authentication.

**Comment by Thulinma** [comment]
Yeah, those additions help a lot in making this more complete, thanks. 👍

Interoperation not being desired at the time was fairly obvious to me, as the way everything works (and explicitly _isn't_ described) makes it clear this was an attempt to lock out non-Adobe software vendors from using more modern codecs and thus gain an advantage over them. I just figured as the algorithm is both public knowledge now **and** no longer serves a practical purpose today (since Flash is dead and all... plus H264 is hardly "modern" anymore) it might be neat to memorialize it here in some way.

The change to be prepared for handshake mismatches like this covers everything that is still relevant today, so I'll let it rest. 😉
